### ISSUE TITLE
Supporting Graphql 2.0.0

### ISSUE THREAD

**Issue by MartinDawson** [graphql-dotnet/relay#7]
Hey,

Are you planning to support graphql 2.0.0?

I tried to upgrade to Graphql 2.0.0-alpha with this package because I wanted to use [subscriptions](https://github.com/graphql-dotnet/server) which requires 2.0.0 but I get a `missingMethodException` for the `Id` function. I tried taking a look at the source but couldn't figure it out.

Thanks.

**Comment by jquense** [comment]
Theoretically, I haven't quite take a look at what stuff has changed there yet

**Comment by jphenow** [comment]
Any movement on this? I can try to take a look as well, though I'm relatively unfamiliar with the code base

**Comment by jquense** [comment]
I haven't updated myself yet, so happy to have some helper there. I don't think it should conflict tho

**Comment by jphenow** [comment]
On further investigation this is an error not necessarily related to a version issue between this and GraphQL lib. I had to to change my NodeGraphType ID (a Guid on my system) to:

```csharp
Id(item => item.Id.ToString());
```

I have some other issues when I use connections, personally - but I suspect I'm messing some pieces up there as well, so I have some more tinkering to do. As far as I can tell, this isn't an issue with _this_ library (or necessarily the other) - just need to fill in some documentation blanks once I get things settled on.

**Comment by MartinDawson** [comment]
Their is no conflict. It works just fine once I upgraded this package to v2 alpha latest. Thanks!

**Comment by lszomoru** [comment]
Any update on this. I have tried to use the latest version of GraphQL (2.0.0-alpha-870) but I was getting `MissingMethodException` on the `Id()` method. Removing both GraphQL and GraphQL.Relay, and then just installing the latest version of GraphQL.Relay resolved the issue. Adding support for GraphQL 2.0.0 would be great. Thanks!

**Comment by MartinDawson** [comment]
@jquense could you update the nuget package please?

**Comment by RehanSaeed** [comment]
Any updates on this? Is this package compatible with GraphQL 2.0? Also, the latest version of [GraphQL.Relay](https://www.nuget.org/packages/GraphQL.Relay/) on NuGet is 0.5.0.

I just found this issue https://github.com/graphql-dotnet/graphql-dotnet/issues/462 discussing adding the relay types directly to the core GraphQL package. And lo and behold, that's where I found them. I don't see the `NodeInterface` type in the GraphQL package though. Perhaps both issues can be closed or even this entire repository if it is deprecated.

**Comment by RehanSaeed** [comment]
It seems only the pagination types have been moved to the core.

**Comment by joemcbride** [comment]
@RahanSaeed you have it a little backwards.  The core Relay types have always been in the main GraphQL project.  That issue is talking about moving them from the main project to this one.

**Comment by RehanSaeed** [comment]
I see, that would make a lot of sense.

As an aside, the `ConnectionBuilder` could really use an `ResolveAsync` method. I'll see if I can raise a PR.

**Comment by MartinDawson** [comment]
@joemcbride What's happening with this... Does the nuget package for this not need updating?

**Comment by jquense** [comment]
ya'll i released the accompanying PR 2 months ago

![image](https://user-images.githubusercontent.com/339286/41256074-8f6365f0-6d96-11e8-85e3-e71f2ea18008.png)

**Comment by MartinDawson** [comment]
I still get the `missingMethodException` though for `Id(x => x.Id)`.

**Comment by ladarit** [comment]
any solution? i use GraphQl 2.4.0 & GraphQl.Realy 0.5.0 and still getting this issue

**Comment by kimdv** [comment]
Did anyone solve this with 2.4.0 ?
